# Generated by Django 4.2.5 on 2023-10-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReactJs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic1', models.CharField(max_length=255)),
                ('topic2', models.CharField(max_length=255)),
            ],
        ),
    ]
