# Generated by Django 4.2.5 on 2023-10-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regi',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
