# Generated by Django 4.2.5 on 2023-10-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='message',
            new_name='review',
        ),
    ]
