# Generated by Django 4.2.5 on 2023-10-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Example_age', models.IntegerField()),
                ('message', models.CharField(max_length=50)),
                ('suggestion', models.CharField(max_length=50)),
            ],
        ),
    ]
