# Generated by Django 4.2.5 on 2023-10-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Example_age',
            new_name='star',
        ),
    ]
