# Generated by Django 4.2.7 on 2023-11-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ourservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Disc', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
